name: Release
permissions:
  contents: write

on:
  push:
    branches:
      - main
      - master

jobs:
  bump-tag-version:
    if: ${{ github.actor != 'dependabot[bot]' }} &&Â  ${{ github.actor != 'pre-commit[bot]' }}
    name: Bump and Tag Version
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      PSONO_CI_API_KEY_ID: ${{ secrets.PSONO_API_KEY_ID }}
      PSONO_CI_API_SECRET_KEY_HEX: ${{ secrets.PSONO_API_SECRET_KEY_HEX }}
      PSONO_CI_SERVER_URL: ${{ vars.PSONO_SERVER_URL }}
      PSONO_GITHUB_TOKEN_ID: ${{ secrets.PSONO_GITHUB_CLI_TOKEN}}

    steps:
      - name: Get GitHub Token
        id: github-token
        uses: jfheinrich-eu/psono-secret-whisperer@b42169213e4392bdd2f1d5a7be76bfeb8c246074 # v1.0.0
        with:
          ci_api_key_id: ${{ secrets.PSONO_API_KEY_ID }}
          ci_api_secret_key_hex: ${{ secrets.PSONO_API_SECRET_KEY_HEX }}
          ci_server_url: ${{ vars.PSONO_SERVER_URL }}
          secret_id: ${{ secrets.PSONO_GITHUB_CLI_TOKEN }}
          secret_type: "secret"
          secret_fields: "password"
          mask_secrets: password

      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - uses: jefflinse/pr-semver-bump@a0f7df89cce6675d4b4cc249327882d1788a726b # v1.7.3
        name: Bump and Tag Version
        with:
          mode: bump
          repo-token: ${{ steps.github-token.outputs.secret1 }}
          major-label: major release
          minor-label: minor release
          patch-label: patch release
          noop-labels: |
            skip-release
            dependencies
          require-release-notes: true
          release-notes-prefix: "<!--- START AUTOGENERATED NOTES --->"
          release-notes-suffix: "<!--- END AUTOGENERATED NOTES --->"
          with-v: false
          base-branch: false
