name: Release
permissions:
  contents: write

on:
  push:
    branches:
      - main
      - master

jobs:
  bump-tag-version:
    if: ${{ github.actor != 'dependabot[bot]' && github.actor != 'pre-commit[bot]' }}
    name: Bump and Tag Version
    runs-on: ubuntu-latest
    timeout-minutes: 30
    defaults:
      run:
        shell: bash

    steps:
      - name: Get GitHub Token
        id: github-token
        uses: jfheinrich-eu/psono-secret-whisperer@ba6cda54d4dfb23d7ff1a2fd4f2dfc87bd833f1f # v1.2.0
        with:
          ci_api_key_id: ${{ secrets.PSONO_API_KEY_ID }}
          ci_api_secret_key_hex: ${{ secrets.PSONO_API_SECRET_KEY_HEX }}
          ci_server_url: ${{ vars.PSONO_SERVER_URL }}
          secret_id: ${{ secrets.PSONO_GITHUB_CLI_TOKEN }}
          secret_type: "secret"
          secret_fields: "password"
          mask_secrets: password

      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - uses: jefflinse/pr-semver-bump@c4e5e589f9f0679723b27abb5f8a5c649e69cf80 # v1.7.4
        name: Bump and Tag Version
        with:
          mode: bump
          repo-token: ${{ steps.github-token.outputs.secret1 }}
          major-label: major release
          minor-label: minor release
          patch-label: patch release
          noop-labels: |
            skip-release
            dependencies
          require-release-notes: true
          release-notes-prefix: "<!--- START AUTOGENERATED NOTES --->"
          release-notes-suffix: "<!--- END AUTOGENERATED NOTES --->"
          with-v: false
          base-branch: false
